<?xml version="1.0?>
<robot xmlns:xacro="https://www.ros.org/wiki/xacro"
name="robot_nano_hand_teleop">

    <xacro:arg name="gazebo" default="false"/>

    <!-- Included URDF/XACRO Files -->

    <xacro:include filename="$(find robot_nano_hand_teleop)/urdf/finger.urdl.xacro" />

    <xacro:property name="M_PI" value="3.14159" />

    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file:///$(find robot_nano_hand_teleop)/models/my_model.stl" scale="1 1 1"/>
            <geometry>
            <material name="green"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file:///$(find robot_nano_hand_teleop)/models/my_model.stl" scale="1 1 1" />
            <geometry>
        </collision>

        <inertial>
            <origin xyz="${-chassisLength/2 +0.2} 0 0.20" rpy= "0 0 0"/>
            <mass value="${baseMass}"/>
            <xacro:box_inertia m="${baseMass}" x="${baseLength}" y="${baseWidth}" z="${baseHeight}" />

        </inertial>

    </link> 



    <!-- Palm link -->


    <!-- Palm joint -->


    <joint name="my_joint" type="continuous">
        <origin xyz="0 0 0.10" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="hood_link" />
        <limit effort="effort_value" velocity="velocity_value" lower="lower_limit" upper="upper_limit" />
    </joint>

    <!-- Macro finger -->

    <xacro:finger parent="base_link" prefix="finger1">
        <origin xyz="0 0 0" rpy="0 0  ${M_PI/2}" />
    <xacro:finger>

<robot>
     

